#pragma once

#define PLAYER_WIDTH 40
#define PLAYER_HEIGHT 50
#define SCORE_BOARD_HEIGHT 150
#define WINDOW_WIDTH PLAYER_WIDTH*10
#define WINDOW_LENGTH WINDOW_WIDTH*1.5 + SCORE_BOARD_HEIGHT
#define ENEMY_WIDTH PLAYER_WIDTH*1.2
#define ENEMY_HEIGHT PLAYER_HEIGHT*0.5
#define MOV_RESOLUTION PLAYER_WIDTH/2 // movement resolution on the screen
#define BULLET_WIDTH 2
#define BULLET_HEIGHT 5
#define MAX_ENEMIES 2